// GENERATED by soundness/db_surface/emit.py from bytecode — do not edit by hand. Regenerate with
// soundness/db_surface/derive.sh, which states the client jars, the wire choke points and the entry types.
package io.poly.candor;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import io.poly.candor.model.Effect;

/**
 * SOUNDNESS R920 — THE Db CLIENT COMMAND SURFACES, DERIVED FROM BYTECODE, CHARGED WHOLE-OWNER MINUS A PURE SET.
 *
 * <p>Consulted by {@link Classifier#classify} only when every hand rule returned null, so it can only turn a
 * null into {@code Db}: no existing charge or carve-out is changed.
 *
 * <p>For each client, a HANDLE TYPE is one reachable from the client's entry type through the return types of
 * public members (and their in-family supertypes, since javac names the static type the caller holds) that has
 * at least one member whose implementation reaches the client's wire choke point (see derive.sh). On a handle
 * type every member is {@code Db} EXCEPT the names listed here, each of which was measured LOCAL in that type:
 * no overload's implementation reaches the choke point, through CHA, lambdas, or an interface with no
 * implementer or a reflective invoke (both counted as reaching it), and none returns a NEW lazy handle (a JDK
 * iterable, collection, stream or I/O type, or a reactive publisher, whose consumption the classifier cannot
 * see). The direction is chosen on purpose: an unlisted or future member is charged, never certified pure.
 */
final class DbClientSurface {
    private DbClientSurface() {}

    private static final Map<String, Set<String>> MONGO = new HashMap<>();
    private static final Map<String, Set<String>> REDISSON = new HashMap<>();
    private static final Map<String, Set<String>> JEDIS = new HashMap<>();
    private static final Map<String, Set<String>> SPRING_REDIS = new HashMap<>();

    private static void put(Map<String, Set<String>> m, String t, String pure) {
        Set<String> s = new HashSet<>();
        if (!pure.isEmpty()) for (String x : pure.split(",")) s.add(x);
        m.put(t, s);
    }

    static {
        put(MONGO, "com.mongodb.client.AggregateIterable", "allowDiskUse,batchSize,bypassDocumentValidation,collation,comment,hint,hintString,let,map,maxAwaitTime,maxTime");
        put(MONGO, "com.mongodb.client.ChangeStreamIterable", "batchSize,collation,comment,fullDocument,fullDocumentBeforeChange,map,maxAwaitTime,resumeAfter,showExpandedEvents,startAfter,startAtOperationTime,withDocumentClass");
        put(MONGO, "com.mongodb.client.ClientSession", "advanceOperationTime,getClusterTime,getOperationTime,getOptions,getOriginator,getPinnedServerAddress,getRecoveryToken,getSnapshotTimestamp,getTransactionContext,getTransactionOptions,hasActiveTransaction,isCausallyConsistent,notifyMessageSent,setRecoveryToken,setSnapshotTimestamp,setTransactionContext");
        put(MONGO, "com.mongodb.client.DistinctIterable", "batchSize,collation,comment,filter,map,maxTime");
        put(MONGO, "com.mongodb.client.FindIterable", "allowDiskUse,batchSize,collation,comment,cursorType,filter,hint,hintString,let,limit,map,max,maxAwaitTime,maxTime,min,noCursorTimeout,partial,projection,returnKey,showRecordId,skip,sort");
        put(MONGO, "com.mongodb.client.ListCollectionNamesIterable", "authorizedCollections,batchSize,comment,filter,map,maxTime");
        put(MONGO, "com.mongodb.client.ListCollectionsIterable", "batchSize,comment,filter,map,maxTime");
        put(MONGO, "com.mongodb.client.ListDatabasesIterable", "authorizedDatabasesOnly,batchSize,comment,filter,map,maxTime,nameOnly");
        put(MONGO, "com.mongodb.client.ListIndexesIterable", "batchSize,comment,map,maxTime");
        put(MONGO, "com.mongodb.client.ListSearchIndexesIterable", "allowDiskUse,batchSize,collation,comment,map,maxTime,name");
        put(MONGO, "com.mongodb.client.MapReduceIterable", "action,batchSize,bypassDocumentValidation,collation,collectionName,databaseName,filter,finalizeFunction,jsMode,limit,map,maxTime,scope,sort,verbose");
        put(MONGO, "com.mongodb.client.MongoChangeStreamCursor", "available,getResumeToken,getServerAddress,getServerCursor");
        put(MONGO, "com.mongodb.client.MongoClient", "getClusterDescription,getDatabase,startSession");
        put(MONGO, "com.mongodb.client.MongoCollection", "getCodecRegistry,getDocumentClass,getNamespace,getReadConcern,getReadPreference,getWriteConcern,withCodecRegistry,withDocumentClass,withReadConcern,withReadPreference,withWriteConcern");
        put(MONGO, "com.mongodb.client.MongoCursor", "available,getServerAddress,getServerCursor");
        put(MONGO, "com.mongodb.client.MongoDatabase", "getCodecRegistry,getCollection,getName,getReadConcern,getReadPreference,getWriteConcern,withCodecRegistry,withReadConcern,withReadPreference,withWriteConcern");
        put(MONGO, "com.mongodb.client.MongoIterable", "batchSize,map");
        put(MONGO, "com.mongodb.client.gridfs.GridFSBucket", "getBucketName,getChunkSizeBytes,getReadConcern,getReadPreference,getWriteConcern,withChunkSizeBytes,withReadConcern,withReadPreference,withWriteConcern");
        put(MONGO, "com.mongodb.client.gridfs.GridFSDownloadStream", "getGridFSFile,mark");
        put(MONGO, "com.mongodb.client.gridfs.GridFSFindIterable", "batchSize,collation,filter,limit,map,maxTime,noCursorTimeout,skip,sort");
        put(MONGO, "com.mongodb.client.gridfs.GridFSUploadStream", "flush,getId,getObjectId");
        put(MONGO, "com.mongodb.client.vault.ClientEncryption", "");
        put(REDISSON, "org.redisson.api.ClusterNodesGroup", "addConnectionListener,removeConnectionListener");
        put(REDISSON, "org.redisson.api.Node", "getAddr,getType");
        put(REDISSON, "org.redisson.api.NodeAsync", "");
        put(REDISSON, "org.redisson.api.NodesGroup", "addConnectionListener,removeConnectionListener");
        put(REDISSON, "org.redisson.api.RAtomicDouble", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RAtomicDoubleAsync", "");
        put(REDISSON, "org.redisson.api.RAtomicDoubleReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RAtomicDoubleRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RAtomicLong", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RAtomicLongAsync", "");
        put(REDISSON, "org.redisson.api.RAtomicLongReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RAtomicLongRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBatch", "getAtomicDouble,getAtomicLong,getBitSet,getBlockingDeque,getBlockingQueue,getBucket,getDeque,getFunction,getGeo,getHyperLogLog,getJsonBucket,getKeys,getLexSortedSet,getList,getListMultimap,getListMultimapCache,getQueue,getScoredSortedSet,getScript,getSet,getSetCache,getSetMultimap,getSetMultimapCache,getShardedTopic,getStream,getTopic");
        put(REDISSON, "org.redisson.api.RBatchReactive", "getAtomicDouble,getAtomicLong,getBitSet,getBlockingDeque,getBlockingQueue,getBucket,getDeque,getFunction,getGeo,getHyperLogLog,getJsonBucket,getKeys,getLexSortedSet,getList,getListMultimap,getQueue,getScoredSortedSet,getScript,getSet,getSetCache,getSetMultimap,getShardedTopic,getStream,getTopic");
        put(REDISSON, "org.redisson.api.RBatchRx", "getAtomicDouble,getAtomicLong,getBitSet,getBlockingDeque,getBlockingQueue,getBucket,getDeque,getFunction,getGeo,getHyperLogLog,getJsonBucket,getKeys,getLexSortedSet,getList,getListMultimap,getListMultimapCache,getQueue,getScoredSortedSet,getScript,getSet,getSetCache,getSetMultimap,getSetMultimapCache,getShardedTopic,getStream,getTopic");
        put(REDISSON, "org.redisson.api.RBinaryStream", "getAsynchronousChannel,getChannel,getCodec,getName");
        put(REDISSON, "org.redisson.api.RBinaryStreamReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBinaryStreamRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBitSet", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBitSetAsync", "");
        put(REDISSON, "org.redisson.api.RBitSetReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBitSetRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBlockingDeque", "getCodec,getName,unsubscribe");
        put(REDISSON, "org.redisson.api.RBlockingDequeAsync", "");
        put(REDISSON, "org.redisson.api.RBlockingDequeReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBlockingDequeRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBlockingQueue", "getCodec,getName,unsubscribe");
        put(REDISSON, "org.redisson.api.RBlockingQueueAsync", "");
        put(REDISSON, "org.redisson.api.RBlockingQueueReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBlockingQueueRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBloomFilter", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBloomFilterAsync", "");
        put(REDISSON, "org.redisson.api.RBloomFilterReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBloomFilterRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBoundedBlockingQueue", "getCodec,getName,unsubscribe");
        put(REDISSON, "org.redisson.api.RBoundedBlockingQueueAsync", "");
        put(REDISSON, "org.redisson.api.RBucket", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBucketAsync", "");
        put(REDISSON, "org.redisson.api.RBucketReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBucketRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RBuckets", "");
        put(REDISSON, "org.redisson.api.RBucketsAsync", "");
        put(REDISSON, "org.redisson.api.RBucketsReactive", "");
        put(REDISSON, "org.redisson.api.RBucketsRx", "");
        put(REDISSON, "org.redisson.api.RCollectionAsync", "");
        put(REDISSON, "org.redisson.api.RCollectionReactive", "");
        put(REDISSON, "org.redisson.api.RCollectionRx", "");
        put(REDISSON, "org.redisson.api.RCountDownLatch", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RCountDownLatchAsync", "");
        put(REDISSON, "org.redisson.api.RCountDownLatchReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RCountDownLatchRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RDelayedQueue", "addAllAsync,addAsync,getCodec,getName");
        put(REDISSON, "org.redisson.api.RDeque", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RDequeAsync", "");
        put(REDISSON, "org.redisson.api.RDequeReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RDequeRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RDestroyable", "");
        put(REDISSON, "org.redisson.api.RDoubleAdder", "add,decrement,getCodec,getName,increment");
        put(REDISSON, "org.redisson.api.RExecutorService", "getName");
        put(REDISSON, "org.redisson.api.RExecutorServiceAsync", "");
        put(REDISSON, "org.redisson.api.RExpirable", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RExpirableAsync", "");
        put(REDISSON, "org.redisson.api.RExpirableReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RExpirableRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RFencedLock", "getName");
        put(REDISSON, "org.redisson.api.RFencedLockAsync", "");
        put(REDISSON, "org.redisson.api.RFencedLockReactive", "getName");
        put(REDISSON, "org.redisson.api.RFencedLockRx", "getName");
        put(REDISSON, "org.redisson.api.RFunction", "");
        put(REDISSON, "org.redisson.api.RFunctionAsync", "");
        put(REDISSON, "org.redisson.api.RFunctionReactive", "");
        put(REDISSON, "org.redisson.api.RFunctionRx", "");
        put(REDISSON, "org.redisson.api.RGeo", "getCodec,getName,stream,unsubscribe");
        put(REDISSON, "org.redisson.api.RGeoAsync", "");
        put(REDISSON, "org.redisson.api.RGeoReactive", "entryIterator,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RGeoRx", "entryIterator,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RHyperLogLog", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RHyperLogLogAsync", "");
        put(REDISSON, "org.redisson.api.RHyperLogLogReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RHyperLogLogRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RIdGenerator", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RIdGeneratorAsync", "");
        put(REDISSON, "org.redisson.api.RIdGeneratorReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RIdGeneratorRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RJsonBucket", "getCodec,getName,size,sizeAsync");
        put(REDISSON, "org.redisson.api.RJsonBucketAsync", "sizeAsync");
        put(REDISSON, "org.redisson.api.RJsonBucketReactive", "getCodec,getName,size");
        put(REDISSON, "org.redisson.api.RJsonBucketRx", "getCodec,getName,size");
        put(REDISSON, "org.redisson.api.RKeys", "");
        put(REDISSON, "org.redisson.api.RKeysAsync", "");
        put(REDISSON, "org.redisson.api.RKeysReactive", "");
        put(REDISSON, "org.redisson.api.RKeysRx", "");
        put(REDISSON, "org.redisson.api.RLexSortedSet", "distributedIterator,getCodec,getName,trySetComparator");
        put(REDISSON, "org.redisson.api.RLexSortedSetAsync", "");
        put(REDISSON, "org.redisson.api.RLexSortedSetReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RLexSortedSetRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RList", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListAsync", "");
        put(REDISSON, "org.redisson.api.RListMultimap", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListMultimapCache", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListMultimapCacheReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListMultimapCacheRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListMultimapReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListMultimapRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RListRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RLiveObjectService", "asLiveObject,isClassRegistered,isLiveObject,unregisterClass");
        put(REDISSON, "org.redisson.api.RLocalCachedMap", "cachedEntrySet,cachedKeySet,cachedValues,getCachedMap,getCodec,getName");
        put(REDISSON, "org.redisson.api.RLocalCachedMapReactive", "cachedEntrySet,cachedKeySet,cachedValues,getCachedMap,getCodec,getName");
        put(REDISSON, "org.redisson.api.RLocalCachedMapRx", "cachedEntrySet,cachedKeySet,cachedValues,getCachedMap,getCodec,getName");
        put(REDISSON, "org.redisson.api.RLock", "getName");
        put(REDISSON, "org.redisson.api.RLockAsync", "");
        put(REDISSON, "org.redisson.api.RLockReactive", "getName");
        put(REDISSON, "org.redisson.api.RLockRx", "getName");
        put(REDISSON, "org.redisson.api.RLongAdder", "add,decrement,getCodec,getName,increment");
        put(REDISSON, "org.redisson.api.RMap", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMapAsync", "");
        put(REDISSON, "org.redisson.api.RMapCache", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMapCacheAsync", "");
        put(REDISSON, "org.redisson.api.RMapCacheReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMapCacheRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMapReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMapRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMultimap", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMultimapAsync", "");
        put(REDISSON, "org.redisson.api.RMultimapCache", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMultimapCacheAsync", "");
        put(REDISSON, "org.redisson.api.RMultimapCacheReactive", "");
        put(REDISSON, "org.redisson.api.RMultimapCacheRx", "");
        put(REDISSON, "org.redisson.api.RMultimapReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RMultimapRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RObject", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RObjectAsync", "");
        put(REDISSON, "org.redisson.api.RObjectReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RObjectRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RPatternTopic", "getPatternNames");
        put(REDISSON, "org.redisson.api.RPatternTopicReactive", "getPatternNames");
        put(REDISSON, "org.redisson.api.RPatternTopicRx", "getPatternNames");
        put(REDISSON, "org.redisson.api.RPermitExpirableSemaphore", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RPermitExpirableSemaphoreAsync", "");
        put(REDISSON, "org.redisson.api.RPermitExpirableSemaphoreReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RPermitExpirableSemaphoreRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RPriorityBlockingDeque", "addAsync,addFirst,addFirstAsync,addFirstIfExists,addFirstIfExistsAsync,addLast,addLastAsync,addLastIfExists,addLastIfExistsAsync,comparator,getCodec,getName,offerAsync,offerFirstAsync,offerLastAsync,poll,pollFirst,pollFirstFromAny,pollFirstFromAnyAsync,pollFromAny,pollFromAnyAsync,pollFromAnyWithName,pollFromAnyWithNameAsync,pollLast,pollLastFromAny,pollLastFromAnyAsync,pushAsync,putAsync,putFirstAsync,putLastAsync,unsubscribe");
        put(REDISSON, "org.redisson.api.RPriorityBlockingQueue", "addAsync,comparator,getCodec,getName,offerAsync,pollFirstFromAny,pollFirstFromAnyAsync,pollFromAny,pollFromAnyAsync,pollFromAnyWithName,pollFromAnyWithNameAsync,pollLastFromAny,pollLastFromAnyAsync,putAsync,unsubscribe");
        put(REDISSON, "org.redisson.api.RPriorityDeque", "addAsync,addFirst,addFirstAsync,addFirstIfExists,addFirstIfExistsAsync,addLast,addLastAsync,addLastIfExists,addLastIfExistsAsync,comparator,getCodec,getName,offerAsync,offerFirstAsync,offerLastAsync,pushAsync");
        put(REDISSON, "org.redisson.api.RPriorityQueue", "addAsync,comparator,getCodec,getName,offerAsync");
        put(REDISSON, "org.redisson.api.RQueue", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RQueueAsync", "");
        put(REDISSON, "org.redisson.api.RQueueReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RQueueRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRateLimiter", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRateLimiterAsync", "");
        put(REDISSON, "org.redisson.api.RRateLimiterReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRateLimiterRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RReliableTopic", "countListeners,getCodec,getName");
        put(REDISSON, "org.redisson.api.RReliableTopicAsync", "");
        put(REDISSON, "org.redisson.api.RReliableTopicReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RReliableTopicRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRemoteService", "deregister,getFreeWorkers");
        put(REDISSON, "org.redisson.api.RRingBuffer", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRingBufferAsync", "");
        put(REDISSON, "org.redisson.api.RRingBufferReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RRingBufferRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RScheduledExecutorService", "getName");
        put(REDISSON, "org.redisson.api.RScheduledExecutorServiceAsync", "");
        put(REDISSON, "org.redisson.api.RScoredSortedSet", "getCodec,getName,stream,unsubscribe");
        put(REDISSON, "org.redisson.api.RScoredSortedSetAsync", "");
        put(REDISSON, "org.redisson.api.RScoredSortedSetReactive", "entryIterator,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RScoredSortedSetRx", "entryIterator,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RScript", "");
        put(REDISSON, "org.redisson.api.RScriptAsync", "");
        put(REDISSON, "org.redisson.api.RScriptReactive", "");
        put(REDISSON, "org.redisson.api.RScriptRx", "");
        put(REDISSON, "org.redisson.api.RSearch", "");
        put(REDISSON, "org.redisson.api.RSearchAsync", "");
        put(REDISSON, "org.redisson.api.RSearchReactive", "");
        put(REDISSON, "org.redisson.api.RSearchRx", "");
        put(REDISSON, "org.redisson.api.RSemaphore", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSemaphoreAsync", "");
        put(REDISSON, "org.redisson.api.RSemaphoreReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSemaphoreRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSet", "getCodec,getName,stream");
        put(REDISSON, "org.redisson.api.RSetAsync", "");
        put(REDISSON, "org.redisson.api.RSetCache", "containsEach,containsEachAsync,destroy,getCodec,getName,readSort,readSortAlpha,readSortAlphaAsync,readSortAsync,removeRandom,removeRandomAsync,sortTo,sortToAsync,stream");
        put(REDISSON, "org.redisson.api.RSetCacheAsync", "containsEachAsync,readSortAlphaAsync,readSortAsync,removeRandomAsync,sortToAsync");
        put(REDISSON, "org.redisson.api.RSetCacheReactive", "destroy,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RSetCacheRx", "destroy,getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RSetMultimap", "entries,getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetMultimapCache", "entries,getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetMultimapCacheReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetMultimapCacheRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetMultimapReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetMultimapRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RSetReactive", "getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RSetRx", "getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RShardedTopic", "countListeners,getChannelNames");
        put(REDISSON, "org.redisson.api.RShardedTopicAsync", "");
        put(REDISSON, "org.redisson.api.RShardedTopicReactive", "getChannelNames");
        put(REDISSON, "org.redisson.api.RShardedTopicRx", "getChannelNames");
        put(REDISSON, "org.redisson.api.RSortable", "");
        put(REDISSON, "org.redisson.api.RSortableAsync", "");
        put(REDISSON, "org.redisson.api.RSortableReactive", "");
        put(REDISSON, "org.redisson.api.RSortableRx", "");
        put(REDISSON, "org.redisson.api.RSortedSet", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RStream", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RStreamAsync", "");
        put(REDISSON, "org.redisson.api.RStreamReactive", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RStreamRx", "getCodec,getName");
        put(REDISSON, "org.redisson.api.RTimeSeries", "destroy,getCodec,getName,stream");
        put(REDISSON, "org.redisson.api.RTimeSeriesAsync", "");
        put(REDISSON, "org.redisson.api.RTimeSeriesReactive", "getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RTimeSeriesRx", "getCodec,getName,iterator");
        put(REDISSON, "org.redisson.api.RTopic", "countListeners,getChannelNames");
        put(REDISSON, "org.redisson.api.RTopicAsync", "");
        put(REDISSON, "org.redisson.api.RTopicReactive", "getChannelNames");
        put(REDISSON, "org.redisson.api.RTopicRx", "getChannelNames");
        put(REDISSON, "org.redisson.api.RTransaction", "getBucket,getBuckets");
        put(REDISSON, "org.redisson.api.RTransactionReactive", "getBucket,getSet,getSetCache");
        put(REDISSON, "org.redisson.api.RTransactionRx", "getBucket,getSet,getSetCache");
        put(REDISSON, "org.redisson.api.RTransferQueue", "addAllAsync,containsAllAsync,containsAsync,getCodec,getName,poll,pollFirstFromAny,pollFirstFromAnyAsync,pollFromAny,pollFromAnyAsync,pollFromAnyWithName,pollFromAnyWithNameAsync,pollLastAndOfferFirstTo,pollLastAndOfferFirstToAsync,pollLastFromAny,pollLastFromAnyAsync,removeAllAsync,removeAsync,retainAllAsync,takeLastAndOfferFirstTo,takeLastAndOfferFirstToAsync,unsubscribe");
        put(REDISSON, "org.redisson.api.RTransferQueueAsync", "addAllAsync,containsAllAsync,containsAsync,pollFirstFromAnyAsync,pollFromAnyAsync,pollFromAnyWithNameAsync,pollLastAndOfferFirstToAsync,pollLastFromAnyAsync,removeAllAsync,removeAsync,retainAllAsync,takeLastAndOfferFirstToAsync");
        put(REDISSON, "org.redisson.api.RTransferQueueReactive", "addAll,contains,containsAll,getCodec,getName,poll,pollFirstFromAny,pollFromAny,pollFromAnyWithName,pollLastAndOfferFirstTo,pollLastFromAny,remove,removeAll,retainAll,takeLastAndOfferFirstTo");
        put(REDISSON, "org.redisson.api.RTransferQueueRx", "addAll,contains,containsAll,getCodec,getName,poll,pollFirstFromAny,pollFromAny,pollFromAnyWithName,pollLastAndOfferFirstTo,pollLastFromAny,remove,removeAll,retainAll,takeLastAndOfferFirstTo");
        put(REDISSON, "org.redisson.api.RedissonClient", "createBatch,createTransaction,getAtomicDouble,getAtomicLong,getBinaryStream,getBitSet,getBloomFilter,getBucket,getBuckets,getClusterNodesGroup,getConfig,getCountDownLatch,getFairLock,getFencedLock,getFunction,getHyperLogLog,getId,getIdGenerator,getJsonBucket,getKeys,getListMultimap,getListMultimapCache,getLiveObjectService,getLock,getMultiLock,getNodesGroup,getPatternTopic,getPermitExpirableSemaphore,getRateLimiter,getReadWriteLock,getRedLock,getRedisNodes,getReliableTopic,getRemoteService,getScript,getSearch,getSemaphore,getSetMultimap,getSetMultimapCache,getShardedTopic,getSpinLock,getStream,getTopic,isShutdown,isShuttingDown");
        put(REDISSON, "org.redisson.api.RedissonReactiveClient", "createBatch,createTransaction,getAtomicDouble,getAtomicLong,getBinaryStream,getBitSet,getBlockingDeque,getBlockingQueue,getBloomFilter,getBucket,getBuckets,getClusterNodesGroup,getConfig,getCountDownLatch,getDeque,getFairLock,getFencedLock,getFunction,getGeo,getHyperLogLog,getId,getIdGenerator,getJsonBucket,getKeys,getLexSortedSet,getList,getListMultimap,getListMultimapCache,getLock,getNodesGroup,getPatternTopic,getPermitExpirableSemaphore,getQueue,getRateLimiter,getReadWriteLock,getRedLock,getReliableTopic,getRemoteService,getRingBuffer,getScoredSortedSet,getScript,getSearch,getSemaphore,getSet,getSetCache,getSetMultimap,getSetMultimapCache,getShardedTopic,getSpinLock,getStream,getTimeSeries,getTopic,isShutdown,isShuttingDown");
        put(REDISSON, "org.redisson.api.RedissonRxClient", "createBatch,createTransaction,getAtomicDouble,getAtomicLong,getBinaryStream,getBitSet,getBlockingDeque,getBlockingQueue,getBloomFilter,getBucket,getBuckets,getClusterNodesGroup,getConfig,getCountDownLatch,getDeque,getFairLock,getFencedLock,getFunction,getGeo,getHyperLogLog,getId,getIdGenerator,getJsonBucket,getKeys,getLexSortedSet,getList,getListMultimap,getListMultimapCache,getLock,getNodesGroup,getPatternTopic,getPermitExpirableSemaphore,getQueue,getRateLimiter,getReadWriteLock,getRedLock,getReliableTopic,getRemoteService,getRingBuffer,getScoredSortedSet,getScript,getSearch,getSemaphore,getSet,getSetCache,getSetMultimap,getSetMultimapCache,getShardedTopic,getSpinLock,getStream,getTimeSeries,getTopic,isShutdown,isShuttingDown");
        put(REDISSON, "org.redisson.api.mapreduce.RCollectionMapReduce", "mapper,reducer,timeout");
        put(REDISSON, "org.redisson.api.mapreduce.RMapReduce", "mapper,reducer,timeout");
        put(REDISSON, "org.redisson.api.mapreduce.RMapReduceExecutor", "");
        put(REDISSON, "org.redisson.api.redisnode.BaseRedisNodes", "");
        put(JEDIS, "redis.clients.jedis.AbstractPipeline", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.AbstractTransaction", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.ClusterPipeline", "getNodeKey,prepareGraphCommands,setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.JedisPooled", "close,getPool,setBroadcastAndRoundRobinConfig,setDefaultSearchDialect,setJsonObjectMapper,setProtocol");
        put(JEDIS, "redis.clients.jedis.JedisSentineled", "close,getCurrentMaster,setBroadcastAndRoundRobinConfig,setDefaultSearchDialect,setJsonObjectMapper,setProtocol");
        put(JEDIS, "redis.clients.jedis.JedisSharding", "close,multi,pipelined,setBroadcastAndRoundRobinConfig,setDefaultSearchDialect,setJsonObjectMapper,setProtocol");
        put(JEDIS, "redis.clients.jedis.MultiNodePipelineBase", "getNodeKey,prepareGraphCommands,setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.Pipeline", "hasPipelinedResponse,setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.PipelineBase", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.PipeliningBase", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.Response", "set,setDependency,toString");
        put(JEDIS, "redis.clients.jedis.ScanIteration", "convertBatchToData,initCommandArguments,isIterationCompleted,isNodeCompleted,nextCommandArguments");
        put(JEDIS, "redis.clients.jedis.ShardedPipeline", "getNodeKey,prepareGraphCommands,setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.Transaction", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.TransactionBase", "setGraphCommands,setJsonObjectMapper");
        put(JEDIS, "redis.clients.jedis.UnifiedJedis", "close,setBroadcastAndRoundRobinConfig,setDefaultSearchDialect,setJsonObjectMapper,setProtocol");
        put(JEDIS, "redis.clients.jedis.bloom.commands.BloomFilterCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.BloomFilterPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.CountMinSketchCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.CountMinSketchPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.CuckooFilterCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.CuckooFilterPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.RedisBloomCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.RedisBloomPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.TDigestSketchCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.TDigestSketchPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.TopKFilterCommands", "");
        put(JEDIS, "redis.clients.jedis.bloom.commands.TopKFilterPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.AccessControlLogBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.AccessControlLogCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.BitBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.BitCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.BitPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.BitPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ClientBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ClientCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ClusterCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ConfigCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ControlBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ControlCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.DatabaseCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.DatabasePipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.FunctionBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.FunctionCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.FunctionPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.FunctionPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.GenericControlCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.GeoBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.GeoCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.GeoPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.GeoPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HashBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HashCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HashPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HashPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HyperLogLogBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HyperLogLogCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HyperLogLogPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.HyperLogLogPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.JedisBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.JedisCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.KeyBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.KeyCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.KeyPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.KeyPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ListBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ListCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ListPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ListPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ModuleCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.PipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.PipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.RedisModuleCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.RedisModulePipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SampleBinaryKeyedCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SampleBinaryKeyedPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SampleKeyedCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SampleKeyedPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ScriptingControlCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ScriptingKeyBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ScriptingKeyCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ScriptingKeyPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ScriptingKeyPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SentinelCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.ServerCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SetBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SetCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SetPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SetPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SlowlogCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SortedSetBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SortedSetCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SortedSetPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.SortedSetPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StreamBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StreamCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StreamPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StreamPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StringBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StringCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StringPipelineBinaryCommands", "");
        put(JEDIS, "redis.clients.jedis.commands.StringPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.gears.RedisGearsCommands", "");
        put(JEDIS, "redis.clients.jedis.graph.RedisGraphCommands", "");
        put(JEDIS, "redis.clients.jedis.graph.RedisGraphPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonCommands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonV1Commands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonV1PipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonV2Commands", "");
        put(JEDIS, "redis.clients.jedis.json.commands.RedisJsonV2PipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.search.FtSearchIteration", "convertBatchToData,initCommandArguments,isIterationCompleted,isNodeCompleted,nextCommandArguments");
        put(JEDIS, "redis.clients.jedis.search.RediSearchCommands", "");
        put(JEDIS, "redis.clients.jedis.search.RediSearchPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.search.aggr.FtAggregateIteration", "convertBatchToData,initCommandArguments,isIterationCompleted,isNodeCompleted,nextCommandArguments");
        put(JEDIS, "redis.clients.jedis.timeseries.RedisTimeSeriesCommands", "");
        put(JEDIS, "redis.clients.jedis.timeseries.RedisTimeSeriesPipelineCommands", "");
        put(JEDIS, "redis.clients.jedis.util.JedisCommandIterationBase", "convertBatchToData,initCommandArguments,isIterationCompleted,isNodeCompleted,nextCommandArguments");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.DefaultedRedisClusterConnection", "clusterCommands,commands,geoCommands,getSubscription,hashCommands,hyperLogLogCommands,isSubscribed,keyCommands,listCommands,multi,scriptingCommands,select,serverCommands,setCommands,streamCommands,stringCommands,unwatch,watch,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.DefaultedRedisConnection", "commands,geoCommands,getSubscription,hashCommands,hyperLogLogCommands,isSubscribed,keyCommands,listCommands,scriptingCommands,serverCommands,setCommands,streamCommands,stringCommands,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterGeoCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterHashCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterHyperLogLogCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterKeyCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterListCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterNumberCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterServerCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterStreamCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterStringCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveClusterZSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveGeoCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveHashCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveHyperLogLogCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveKeyCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveListCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveNumberCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactivePubSubCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveRedisClusterConnection", "geoCommands,hashCommands,hyperLogLogCommands,keyCommands,listCommands,numberCommands,pubSubCommands,scriptingCommands,serverCommands,setCommands,streamCommands,stringCommands,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveRedisConnection", "geoCommands,hashCommands,hyperLogLogCommands,keyCommands,listCommands,numberCommands,pubSubCommands,scriptingCommands,serverCommands,setCommands,streamCommands,stringCommands,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveScriptingCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveServerCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveStreamCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveStringCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.ReactiveZSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisClusterCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisClusterConnection", "clusterCommands,commands,geoCommands,getSubscription,hashCommands,hyperLogLogCommands,isClosed,isPipelined,isQueueing,isSubscribed,keyCommands,listCommands,multi,scriptingCommands,select,serverCommands,setCommands,streamCommands,stringCommands,unwatch,watch,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisClusterServerCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisCommands", "getSubscription,isSubscribed");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisConnection", "commands,geoCommands,getSubscription,hashCommands,hyperLogLogCommands,isPipelined,isQueueing,isSubscribed,keyCommands,listCommands,scriptingCommands,serverCommands,setCommands,streamCommands,stringCommands,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisConnectionCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisConnectionFactory", "getConvertPipelineAndTxResults");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisGeoCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisHashCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisHyperLogLogCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisKeyCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisListCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisPubSubCommands", "getSubscription,isSubscribed");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisScriptingCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisSentinelCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisSentinelConnection", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisServerCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisStreamCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisStringCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisTxCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.RedisZSetCommands", "");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.StringRedisConnection", "commands,geoCommands,getSubscription,hashCommands,hyperLogLogCommands,isPipelined,isQueueing,isSubscribed,keyCommands,listCommands,scriptingCommands,serverCommands,setCommands,streamCommands,stringCommands,zSetCommands");
        put(SPRING_REDIS, "org.springframework.data.redis.connection.Subscription", "getChannels,getListener,getPatterns,isAlive");
    }

    /** org.redisson.api types MEASURED and found to be no handle (futures, options, results): never charged. */
    private static final Set<String> REDISSON_NOT_HANDLE = Set.of(
            "org.redisson.api.RCascadeType",
            "org.redisson.api.RExecutorBatchFuture",
            "org.redisson.api.RExecutorFuture",
            "org.redisson.api.RFuture",
            "org.redisson.api.RLiveObject",
            "org.redisson.api.RReadWriteLock",
            "org.redisson.api.RReadWriteLockReactive",
            "org.redisson.api.RReadWriteLockRx",
            "org.redisson.api.RScheduledFuture",
            "org.redisson.api.RType");

    /** org.springframework.data.redis.connection types measured and found to be no handle. */
    private static final Set<String> SPRING_REDIS_NOT_HANDLE = Set.of(
            "org.springframework.data.redis.connection.AbstractRedisConnection",
            "org.springframework.data.redis.connection.BitFieldSubCommands",
            "org.springframework.data.redis.connection.ClusterCommandExecutionFailureException",
            "org.springframework.data.redis.connection.ClusterCommandExecutor",
            "org.springframework.data.redis.connection.ClusterInfo",
            "org.springframework.data.redis.connection.ClusterNodeResourceProvider",
            "org.springframework.data.redis.connection.ClusterSlotHashUtil",
            "org.springframework.data.redis.connection.ClusterTopology",
            "org.springframework.data.redis.connection.ClusterTopologyProvider",
            "org.springframework.data.redis.connection.ConnectionUtils",
            "org.springframework.data.redis.connection.DataType",
            "org.springframework.data.redis.connection.DecoratedRedisConnection",
            "org.springframework.data.redis.connection.DefaultMessage",
            "org.springframework.data.redis.connection.DefaultSortParameters",
            "org.springframework.data.redis.connection.DefaultStringRedisConnection",
            "org.springframework.data.redis.connection.DefaultStringTuple",
            "org.springframework.data.redis.connection.FutureResult",
            "org.springframework.data.redis.connection.Limit",
            "org.springframework.data.redis.connection.Message",
            "org.springframework.data.redis.connection.MessageListener",
            "org.springframework.data.redis.connection.NamedNode",
            "org.springframework.data.redis.connection.PoolException",
            "org.springframework.data.redis.connection.ReactiveClusterScriptingCommands",
            "org.springframework.data.redis.connection.ReactiveRedisConnectionFactory",
            "org.springframework.data.redis.connection.ReactiveSubscription",
            "org.springframework.data.redis.connection.RedisClusterCommandsProvider",
            "org.springframework.data.redis.connection.RedisClusterConfiguration",
            "org.springframework.data.redis.connection.RedisClusterNode",
            "org.springframework.data.redis.connection.RedisCommandsProvider",
            "org.springframework.data.redis.connection.RedisConfiguration",
            "org.springframework.data.redis.connection.RedisInvalidSubscriptionException",
            "org.springframework.data.redis.connection.RedisNode",
            "org.springframework.data.redis.connection.RedisPassword",
            "org.springframework.data.redis.connection.RedisPipelineException",
            "org.springframework.data.redis.connection.RedisSentinelConfiguration",
            "org.springframework.data.redis.connection.RedisServer",
            "org.springframework.data.redis.connection.RedisSocketConfiguration",
            "org.springframework.data.redis.connection.RedisStandaloneConfiguration",
            "org.springframework.data.redis.connection.RedisStaticMasterReplicaConfiguration",
            "org.springframework.data.redis.connection.RedisSubscribedConnectionException",
            "org.springframework.data.redis.connection.ReturnType",
            "org.springframework.data.redis.connection.SortParameters",
            "org.springframework.data.redis.connection.SubscriptionListener",
            "org.springframework.data.redis.connection.ValueEncoding");

    /** Lettuce command interfaces outside {@code io.lettuce.core.api.} (cluster, pub/sub, sentinel): local
     *  wherever an implementation exists in lettuce-core 6.3.2 (the sync and coroutine APIs are proxies). */
    private static final Set<String> LETTUCE_PURE = Set.of(
            "all", "digest", "flushCommands", "getConnection", "getStatefulConnection", "isOpen", "nodes",
            "readonly", "setAutoFlushCommands", "setTimeout", "upstream");

    /** The identity accessors every Redisson object exposes, for a type this table did not measure. */
    private static final Set<String> REDISSON_DEFAULT_PURE = Set.of("getName", "getCodec");

    static Effect classify(String owner, String method) {
        Effect e = classify0(owner, method);
        // REACH for the corpus A/B (CANDOR_MASK_DEBUG): one line per Db this table supplied.
        if (e != null && Candor.MASK_DEBUG) System.err.println("R920SURF	" + owner + "." + method);
        return e;
    }

    private static Effect classify0(String owner, String method) {
        if (method.equals("<init>") || method.equals("<clinit>") || Candor.isConventionallyPure(method)) return null;
        Set<String> p;
        if ((p = MONGO.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = JEDIS.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = REDISSON.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = SPRING_REDIS.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        // org.redisson and org.springframework are kappa-COVERED packages: an unmodelled member there is
        // certified pure, not disclosed. So a handle-shaped type this table did not measure (a newer client
        // version) defaults to Db rather than to silence.
        if (owner.startsWith("org.redisson.api.R") && owner.length() > 18 && Character.isUpperCase(owner.charAt(18))
                && owner.indexOf('.', 18) < 0 && owner.indexOf('$') < 0 && !REDISSON_NOT_HANDLE.contains(owner))
            return REDISSON_DEFAULT_PURE.contains(method) ? null : Effect.DB;
        if (owner.startsWith("org.springframework.data.redis.connection.") && owner.lastIndexOf('.') == 41 && owner.indexOf('$') < 0
                && (owner.endsWith("Commands") || owner.endsWith("Connection")) && !SPRING_REDIS_NOT_HANDLE.contains(owner))
            return Effect.DB;
        if (owner.startsWith("io.lettuce.core.") && owner.contains(".api.") && owner.endsWith("Commands"))
            return LETTUCE_PURE.contains(method) ? null : Effect.DB;
        // Datastax: the CqlSession verbs (charged in Classifier) on the session supertypes a caller may hold.
        if ((owner.equals("com.datastax.oss.driver.api.core.session.Session")
                || owner.equals("com.datastax.oss.driver.api.core.cql.SyncCqlSession")
                || owner.equals("com.datastax.oss.driver.api.core.cql.AsyncCqlSession"))
                && (method.startsWith("execute") || method.startsWith("prepare") || method.startsWith("checkSchemaAgreement")))
            return Effect.DB;
        return null;
    }
}
