#!/usr/bin/env bash
# SOUNDNESS R1094 — regenerate the three derived JDK indexes the engine ships, from PINNED JDK images.
#
#   bash soundness/jdk_index/derive.sh           # rewrite src/main/resources/candor/jdk-*.idx.gz + manifest.txt
#   bash soundness/jdk_index/derive.sh --check   # regenerate to a temp dir; exit 1 on ANY drift (compares TEXT)
#
# Until R1094 these were written by build.gradle.kts from `jrt:/` of the GRADLE DAEMON's JVM — not the toolchain,
# not a named JDK. Measured: the published v0.40.3 jar's indexes are byte-identical to a build whose daemon ran
# Corretto 17.0.14 (this machine's default JAVA_HOME), and differ from a JDK 21 build of the same commit. So the
# engine's knowledge of the JDK's functional interfaces (R191) and invoking HOFs (R237) was a property of the
# releaser's shell. Now the build copies the checked-in files, and this script is the only thing that writes them.
#
# INPUTS, and nothing else: images.tsv (Temurin 21 and 25, Linux/macOS/Windows; URL + SHA-256 — a mismatch is
# REFUSED), asm.tsv (the ASM jars the generator runs on, same rule), JdkIndexGen.java and this script. Their hash is
# the manifest's generator-sha256, which JdkIndexPinTest re-derives on every push alongside each index's
# content-sha256. The generator runs on the HOST's pinned JDK 25 image (a newer runtime can open an older image's
# jrt:/, not the reverse); CANDOR_JDK_INDEX_JAVA overrides that on a host the list has no image for.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/../.." && pwd)"
CACHE="${CANDOR_JDK_INDEX_CACHE:-$HERE/images}"
CHECK=0; if [ "${1:-}" = "--check" ]; then CHECK=1; fi
RES="$ROOT/src/main/resources/candor"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$CACHE" "$WORK/tool" "$WORK/out"

fetch() {   # fetch <file> <url> <sha256>
  local f="$1" url="$2" sha="$3"
  if [ ! -s "$CACHE/$f" ]; then curl -fsSL --retry 3 -o "$CACHE/$f.part" "$url" && mv "$CACHE/$f.part" "$CACHE/$f"; fi
  local got; got="$(shasum -a 256 "$CACHE/$f" | cut -d' ' -f1)"
  if [ "$got" != "$sha" ]; then echo "jdk-index: $f is $got, the pin is $sha — refusing" >&2; exit 1; fi
}

# 1. ASM
CP=""
while IFS=$'\t' read -r jar url sha; do
  [ -z "$jar" ] && continue
  fetch "$jar" "$url" "$sha"; CP="$CP${CP:+:}$CACHE/$jar"
done < "$HERE/asm.tsv"

# 2. the images: each unpacked once under $CACHE/<name>/, java.home located by its `release` file
case "$(uname -s)-$(uname -m)" in
  Darwin-arm64) HOST=mac-aarch64 ;;
  Linux-x86_64) HOST=linux-x64 ;;
  *) HOST=none ;;
esac
HOMES=(); RUNTIME=""
while IFS=$'\t' read -r name kind url sha; do
  [ -z "$name" ] && continue
  arc="$name.${kind/tar/tar.gz}"
  fetch "$arc" "$url" "$sha"
  if [ ! -d "$CACHE/$name" ]; then
    mkdir -p "$CACHE/$name.part"
    if [ "$kind" = zip ]; then unzip -q "$CACHE/$arc" -d "$CACHE/$name.part"; else tar xzf "$CACHE/$arc" -C "$CACHE/$name.part"; fi
    mv "$CACHE/$name.part" "$CACHE/$name"
  fi
  rel="$(find "$CACHE/$name" -maxdepth 4 -name release -type f | head -1)"
  [ -n "$rel" ] || { echo "jdk-index: no java.home under $CACHE/$name" >&2; exit 1; }
  home="$(dirname "$rel")"; HOMES+=("$home")
  case "$name" in temurin-25*-"$HOST") RUNTIME="$home/bin/java" ;; esac
done < "$HERE/images.tsv"
RUNTIME="${CANDOR_JDK_INDEX_JAVA:-$RUNTIME}"
[ -x "$RUNTIME" ] || { echo "jdk-index: no JDK 25 runtime for host $HOST — set CANDOR_JDK_INDEX_JAVA" >&2; exit 1; }

# 3. derive and union
"$(dirname "$RUNTIME")/javac" -nowarn -cp "$CP" -d "$WORK/tool" "$HERE/JdkIndexGen.java"
env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS \
  "$RUNTIME" -Xmx6g -cp "$WORK/tool:$CP" JdkIndexGen --union "$WORK/out" "${HOMES[@]}"

GSHA="$(cat "$HERE/JdkIndexGen.java" "$HERE/derive.sh" "$HERE/images.tsv" "$HERE/asm.tsv" | shasum -a 256 | cut -d' ' -f1)"
{
  echo "# SOUNDNESS R1094 — the derived JDK indexes shipped in src/main/resources/candor/. GENERATED by"
  echo "# soundness/jdk_index/derive.sh from the images in images.tsv; DO NOT EDIT. content-sha256 is of the"
  echo "# DECOMPRESSED text (gzip bytes depend on the zlib that wrote them); JdkIndexPinTest checks both lines."
  echo "generator-sha256 $GSHA"
  for f in jdk-supertypes.idx jdk-sams.idx jdk-hof-invokes.idx jdk-functional.idx; do
    t="$(gzip -dc "$WORK/out/$f.gz" | shasum -a 256 | cut -d' ' -f1)"
    n="$(gzip -dc "$WORK/out/$f.gz" | awk 'END{print NR}')"
    echo "$f $t $n"
  done
} > "$WORK/manifest.txt"

if [ "$CHECK" = 1 ]; then
  bad=0
  for f in jdk-supertypes.idx jdk-sams.idx jdk-hof-invokes.idx jdk-functional.idx; do
    if ! cmp -s <(gzip -dc "$WORK/out/$f.gz") <(gzip -dc "$RES/$f.gz"); then
      echo "jdk-index --check: $RES/$f.gz is NOT what the pinned images generate:" >&2
      diff <(gzip -dc "$RES/$f.gz") <(gzip -dc "$WORK/out/$f.gz") | head -10 >&2; bad=1
    fi
  done
  if ! cmp -s "$WORK/manifest.txt" "$HERE/manifest.txt"; then
    echo "jdk-index --check: manifest.txt differs:" >&2; diff "$HERE/manifest.txt" "$WORK/manifest.txt" >&2 || true; bad=1
  fi
  [ "$bad" = 0 ] && echo "jdk-index --check: the indexes and manifest.txt reproduce from the pinned images"
  exit "$bad"
fi
for f in jdk-supertypes.idx jdk-sams.idx jdk-hof-invokes.idx jdk-functional.idx; do cp "$WORK/out/$f.gz" "$RES/$f.gz"; done
cp "$WORK/manifest.txt" "$HERE/manifest.txt"
echo "jdk-index: wrote $RES/jdk-{supertypes,sams,hof-invokes,functional}.idx.gz and $HERE/manifest.txt — read the diff"
