import sys,re,collections
def load(path, drop=()):
    out={}
    for l in open(path):
        t,w,lz,p,n,pure=l.rstrip('\n').split('\t')
        if t in drop: continue
        out[t.replace('/','.')]=sorted(x for x in pure.split(',') if x)
    return out
def measured(path, rx):
    # every public API type the derivation SAW, members or not (an enum has only statics), from super.tsv
    s=set()
    for l in open(path.replace('reach.tsv','super.tsv')):
        if l.startswith('#SUPER'):
            t=l.split('\t')[1]
            if re.match(rx,t): s.add(t.replace('/','.'))
    return s
mongo=load('mongo/handles.tsv')
redisson=load('redisson/handles.tsv')
jedis=load('jedis/handles.tsv', drop={'redis/clients/jedis/Jedis','redis/clients/jedis/JedisCluster','redis/clients/jedis/JedisPool','redis/clients/jedis/JedisSentinelPool','redis/clients/jedis/util/Pool','redis/clients/jedis/Connection'})
sdr=load('sdr/handles.tsv', drop={'org/springframework/data/redis/connection/MessageListener'})
red_measured=measured('redisson/reach.tsv', r'org/redisson/api/R[A-Z]')-set(redisson)
sdr_measured=measured('sdr/reach.tsv', r'org/springframework/data/redis/connection/[^/]+$')-set(sdr)
def block(name, d):
    lines=[]
    for t in sorted(d):
        lines.append(f'        put({name}, "{t}", "{",".join(d[t])}");')
    return '\n'.join(lines)
def setlit(s):
    s=sorted(s); return ',\n'.join('            "%s"'%x for x in s)
print(f'''// GENERATED by soundness/db_surface/emit.py from bytecode — do not edit by hand. Regenerate with
// soundness/db_surface/derive.sh, which states the client jars, the wire choke points and the entry types.
package io.poly.candor;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import io.poly.candor.model.Effect;

/**
 * SOUNDNESS R920 — THE Db CLIENT COMMAND SURFACES, DERIVED FROM BYTECODE, CHARGED WHOLE-OWNER MINUS A PURE SET.
 *
 * <p>Consulted by {{@link Classifier#classify}} only when every hand rule returned null, so it can only turn a
 * null into {{@code Db}}: no existing charge or carve-out is changed.
 *
 * <p>For each client, a HANDLE TYPE is one reachable from the client's entry type through the return types of
 * public members (and their in-family supertypes, since javac names the static type the caller holds) that has
 * at least one member whose implementation reaches the client's wire choke point (see derive.sh). On a handle
 * type every member is {{@code Db}} EXCEPT the names listed here, each of which was measured LOCAL in that type:
 * no overload's implementation reaches the choke point, through CHA, lambdas, or an interface with no
 * implementer or a reflective invoke (both counted as reaching it), and none returns a NEW lazy handle (a JDK
 * iterable, collection, stream or I/O type, or a reactive publisher, whose consumption the classifier cannot
 * see). The direction is chosen on purpose: an unlisted or future member is charged, never certified pure.
 */
final class DbClientSurface {{
    private DbClientSurface() {{}}

    private static final Map<String, Set<String>> MONGO = new HashMap<>();
    private static final Map<String, Set<String>> REDISSON = new HashMap<>();
    private static final Map<String, Set<String>> JEDIS = new HashMap<>();
    private static final Map<String, Set<String>> SPRING_REDIS = new HashMap<>();

    private static void put(Map<String, Set<String>> m, String t, String pure) {{
        Set<String> s = new HashSet<>();
        if (!pure.isEmpty()) for (String x : pure.split(",")) s.add(x);
        m.put(t, s);
    }}

    static {{
{block('MONGO', mongo)}
{block('REDISSON', redisson)}
{block('JEDIS', jedis)}
{block('SPRING_REDIS', sdr)}
    }}

    /** org.redisson.api types MEASURED and found to be no handle (futures, options, results): never charged. */
    private static final Set<String> REDISSON_NOT_HANDLE = Set.of(
{setlit(red_measured)});

    /** org.springframework.data.redis.connection types measured and found to be no handle. */
    private static final Set<String> SPRING_REDIS_NOT_HANDLE = Set.of(
{setlit(sdr_measured)});

    /** Lettuce command interfaces outside {{@code io.lettuce.core.api.}} (cluster, pub/sub, sentinel): local
     *  wherever an implementation exists in lettuce-core 6.3.2 (the sync and coroutine APIs are proxies). */
    private static final Set<String> LETTUCE_PURE = Set.of(
            "all", "digest", "flushCommands", "getConnection", "getStatefulConnection", "isOpen", "nodes",
            "readonly", "setAutoFlushCommands", "setTimeout", "upstream");

    /** The identity accessors every Redisson object exposes, for a type this table did not measure. */
    private static final Set<String> REDISSON_DEFAULT_PURE = Set.of("getName", "getCodec");

    static Effect classify(String owner, String method) {{
        Effect e = classify0(owner, method);
        // REACH for the corpus A/B (CANDOR_MASK_DEBUG): one line per Db this table supplied.
        if (e != null && Candor.MASK_DEBUG) System.err.println("R920SURF\t" + owner + "." + method);
        return e;
    }}

    /** {{@link #classify}} without the reach mark, for a caller asking where a charge CAME from. */
    static Effect classifyQuiet(String owner, String method) {{
        return classify0(owner, method);
    }}

    private static Effect classify0(String owner, String method) {{
        if (method.equals("<init>") || method.equals("<clinit>") || Candor.isConventionallyPure(method)) return null;
        Set<String> p;
        if ((p = MONGO.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = JEDIS.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = REDISSON.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        if ((p = SPRING_REDIS.get(owner)) != null) return p.contains(method) ? null : Effect.DB;
        // org.redisson and org.springframework are kappa-COVERED packages: an unmodelled member there is
        // certified pure, not disclosed. So a handle-shaped type this table did not measure (a newer client
        // version) defaults to Db rather than to silence.
        if (owner.startsWith("org.redisson.api.R") && owner.length() > 18 && Character.isUpperCase(owner.charAt(18))
                && owner.indexOf('.', 18) < 0 && owner.indexOf('$') < 0 && !REDISSON_NOT_HANDLE.contains(owner))
            return REDISSON_DEFAULT_PURE.contains(method) ? null : Effect.DB;
        if (owner.startsWith("org.springframework.data.redis.connection.") && owner.lastIndexOf('.') == 41 && owner.indexOf('$') < 0
                && (owner.endsWith("Commands") || owner.endsWith("Connection")) && !SPRING_REDIS_NOT_HANDLE.contains(owner))
            return Effect.DB;
        if (owner.startsWith("io.lettuce.core.") && owner.contains(".api.") && owner.endsWith("Commands"))
            return LETTUCE_PURE.contains(method) ? null : Effect.DB;
        // Datastax: the CqlSession verbs (charged in Classifier) on the session supertypes a caller may hold.
        if ((owner.equals("com.datastax.oss.driver.api.core.session.Session")
                || owner.equals("com.datastax.oss.driver.api.core.cql.SyncCqlSession")
                || owner.equals("com.datastax.oss.driver.api.core.cql.AsyncCqlSession"))
                && (method.startsWith("execute") || method.startsWith("prepare") || method.startsWith("checkSchemaAgreement")))
            return Effect.DB;
        return null;
    }}
}}''')
