#!/usr/bin/env python3
"""Construction-based soundness fuzzer for candor-java (sibling of the Rust impl's soundness/gen.py).

Generates a compilable Java class that threads a KNOWN effect (Fs/Net/Exec/Env) from a `sink` method up
through a random chain of methods, where each call edge uses a randomly-chosen JVM CALL FORM — the ways
an effect can reach a method on the JVM: a direct static call, a lambda, a method reference, a
constructor (`<init>`), a static initializer (`<clinit>`), interface/virtual dispatch (CHA), and an
anonymous class.

Every emitted method transitively reaches the effect, so candor-java must report each `Gen.fNN` / `sink`
/ `main` with the effect in its `inferred` set OR with `Unknown` (a sound over-approximation). A method
reported pure — or omitted from the report (candor omits pure methods) — is a SILENT UNDER-REPORT: the
bug class this harness exists to catch. truth.json lists the methods that must be effect-or-Unknown;
run.sh checks the report against it.

Usage:  gen.py <seed> <out-dir>     # writes <out-dir>/Gen.java + truth.json
"""
import json
import os
import random
import sys

# effect -> the Java statement that performs it (caught so the generated code compiles & is well-formed).
EFFECTS = {
    "Fs":   'try { java.nio.file.Files.readAllBytes(java.nio.file.Path.of("/tmp/candor_fuzz")); } catch (Exception e) {}',
    "Net":  'try { java.net.Socket s = new java.net.Socket("127.0.0.1", 9); s.close(); } catch (Exception e) {}',
    "Exec": 'try { new ProcessBuilder("echo", "x").start(); } catch (Exception e) {}',
    "Env":  'System.getenv("CANDOR_FUZZ");',
}


# Each edge form returns (body_calling_callee, extra_nested_items). The body is the statement(s) that
# reach `callee`; the items are nested types emitted inside `Gen` (a per-edge ctor/clinit/iface).
def edge_forms(callee, i):
    return {
        # direct static call (invokestatic).
        "direct":    (f"{callee}();", []),
        # lambda: the body's effect is in a `lambda$` synthetic, edged via the invokedynamic Handle.
        "lambda":    (f"Runnable r{i} = () -> {callee}(); r{i}.run();", []),
        # method reference to a static method (invokedynamic Handle straight to `callee`).
        "methodref": (f"Runnable r{i} = Gen::{callee}; r{i}.run();", []),
        # constructor: the effect lives in `<init>`, reached by `new Ctor{i}()`.
        "ctor":      (f"new Ctor{i}();",
                      [f"static class Ctor{i} {{ Ctor{i}() {{ {callee}(); }} }}"]),
        # static initializer: the effect lives in `<clinit>`, reached by a static call that loads the class.
        "clinit":    (f"Clinit{i}.touch();",
                      [f"static class Clinit{i} {{ static {{ {callee}(); }} static void touch() {{}} }}"]),
        # interface dispatch: resolved by CHA to the concrete impl whose method calls `callee`.
        "iface":     (f"I{i} x{i} = new Impl{i}(); x{i}.run();",
                      [f"interface I{i} {{ void run(); }}",
                       f"static class Impl{i} implements I{i} {{ public void run() {{ {callee}(); }} }}"]),
        # anonymous class implementing Runnable (a distinct synthesized class, resolved by CHA).
        "anon":      (f"Runnable r{i} = new Runnable() {{ public void run() {{ {callee}(); }} }}; r{i}.run();", []),
    }


def main():
    seed = int(sys.argv[1])
    out = sys.argv[2]
    rng = random.Random(seed)

    allowed = os.environ.get("CANDOR_FUZZ_EFFECTS", "").split() or list(EFFECTS)
    effect = rng.choice([e for e in EFFECTS if e in allowed])
    only_forms = os.environ.get("CANDOR_FUZZ_FORMS", "").split()
    n = rng.randint(3, 8)  # chain length

    fns = [f"f{i:02d}" for i in range(n)]
    bodies = {}
    items = []
    forms_log = {}
    for i in range(n):
        callee = fns[i + 1] if i + 1 < n else "sink"
        forms = edge_forms(callee, i)
        choices = [f for f in forms if f in only_forms] if only_forms else list(forms)
        form = rng.choice(choices)
        body, extra = forms[form]
        bodies[fns[i]] = body
        items.extend(extra)
        forms_log[fns[i]] = form

    lines = [f"// GENERATED by soundness/gen.py — do not edit. seed={seed} effect={effect}",
             "public class Gen {",
             f"    static void sink() {{ {EFFECTS[effect]} }}"]
    for f in fns:
        lines.append(f"    static void {f}() {{ {bodies[f]} }}")
    lines.append(f"    public static void main(String[] a) {{ {fns[0]}(); }}")
    for it in items:
        lines.append(f"    {it}")
    lines.append("}")
    src = "\n".join(lines) + "\n"

    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "Gen.java"), "w") as f:
        f.write(src)
    # Methods that MUST be effect-or-Unknown (candor-java names them `Gen.<method>`).
    expect = sorted([f"Gen.{x}" for x in fns] + ["Gen.sink", "Gen.main"])
    with open(os.path.join(out, "truth.json"), "w") as f:
        json.dump({"seed": seed, "effect": effect, "expect": expect, "forms": forms_log}, f, indent=2)


if __name__ == "__main__":
    main()
