#!/usr/bin/env bash
# SOUNDNESS R492/R727 — regenerate src/main/resources/candor/framework-reach.tsv from the framework jars' bytecode.
#
#   bash soundness/kappa_table/derive.sh <candor-java-all.jar>            # rewrite the table (+ witness.tsv)
#   bash soundness/kappa_table/derive.sh --check <candor-java-all.jar>    # regenerate to a temp dir; exit 1 on ANY drift
#
# witness.tsv (~130 MB, gitignored — regenerate it, never trust a stale copy) gives, for every charged
# (member, effect), the resolved path from the member to the body this engine's scan charged with that effect.
# Its DIVERGENT lines are the charges present in one surveyed version of an artefact and not another — charged
# nowhere.
#
# INPUTS, and nothing else: the jars named in sources.tsv (Maven Central coordinate + SHA-256 — a jar whose bytes
# differ is REFUSED, never used), this script, FrameworkReachGen.java, and the engine jar given as the argument.
# Same inputs -> byte-identical table. The engine is an input on purpose: the table is built from ITS `direct`
# effects, so a classifier change that moves a charge makes `--check` fail until the table is regenerated.
#
# Steps: fetch/verify every jar; scan each with the engine under -Dcandor.frameworkReach=off (the table never
# feeds its own generation); close every consumer-callable member of every public class under a
# Rules.KAPPA_COVERED_PREFIXES prefix over statically-resolved edges (FrameworkReachGen.java says exactly which);
# write the table, whose header records sources.tsv and the generator checksum, and witness.tsv.
# Read the diff before committing: every new row is a new charge on every caller of that member.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/../.." && pwd)"
LIB="${CANDOR_SOUNDNESS_LIB:-$ROOT/soundness/lib}"
CHECK=0; if [ "${1:-}" = "--check" ]; then CHECK=1; shift; fi
JAR="$(cd "$(dirname "${1:?usage: derive.sh [--check] <candor-java-all.jar>}")" && pwd)/$(basename "$1")"
J="${JAVA_HOME:-/opt/homebrew/opt/openjdk@21}/bin"
JOBS="${JOBS:-6}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$LIB" "$WORK/rep" "$WORK/tool"

# 1. sources: fetch what is missing, refuse what does not match
while IFS=$'\t' read -r jar coord url sha; do
  [ -z "$jar" ] && continue
  if [ ! -s "$LIB/$jar" ]; then curl -fsSL --retry 3 -o "$LIB/$jar.part" "$url" && mv "$LIB/$jar.part" "$LIB/$jar"; fi
  got="$(shasum -a 256 "$LIB/$jar" | cut -d' ' -f1)"
  if [ "$got" != "$sha" ]; then echo "derive: $jar is $got, sources.tsv pins $sha ($coord) — refusing" >&2; exit 1; fi
done < "$HERE/sources.tsv"

# 2. the engine's own scan of each jar, table OFF
export J JAR LIB WORK
cut -f1 "$HERE/sources.tsv" | sed '/^$/d' | (cd "$WORK" && xargs -P "$JOBS" -n 1 sh -c \
  '"$J/java" -Xmx4g -Dcandor.frameworkReach=off -jar "$JAR" "$LIB/$0" --json "$WORK/rep/$0.json" >/dev/null 2>"$WORK/rep/$0.err" || { echo "derive: scan of $0 failed" >&2; exit 255; }')
for jar in $(cut -f1 "$HERE/sources.tsv"); do
  [ -s "$WORK/rep/$jar.json" ] || { echo "derive: no report for $jar" >&2; exit 1; }
done

# 3. header: the generator checksum and every source, so a table always says what it was built from
GSHA="$(cat "$HERE/FrameworkReachGen.java" "$HERE/derive.sh" "$HERE/sources.tsv" | shasum -a 256 | cut -d' ' -f1)"
{
  echo "# candor framework-reach table — GENERATED by soundness/kappa_table/derive.sh; DO NOT EDIT (SOUNDNESS R492/R727)."
  echo "# owner.name+desc <TAB> effects: in every surveyed artefact declaring the owner, the statically-resolved body"
  echo "# reaches a body this engine's scan charged with those effects (direct, concrete only). A member with NO row"
  echo "# is not claimed pure: it keeps the treatment it had without this table."
  echo "# NAMED MISS: the closure stops at the JDK, which is OPAQUE here (no bodies; only the classifier's name rules),"
  echo "# while framework bodies are TRANSPARENT. A framework member whose effect happens inside a JDK body the"
  echo "# classifier leaves uncharged is missed exactly as a direct call to that JDK member is (R814 is that frontier)."
  echo "# generator-sha256 $GSHA"
  while IFS=$'\t' read -r jar coord url sha; do [ -n "$jar" ] && echo "# source $coord $sha"; done < "$HERE/sources.tsv"
} > "$WORK/header"

# 4. generate
"$J/javac" -nowarn -cp "$JAR" -d "$WORK/tool" "$HERE/FrameworkReachGen.java"
ARGS=()
for jar in $(cut -f1 "$HERE/sources.tsv"); do ARGS+=("$LIB/$jar" "$WORK/rep/$jar.json"); done
"$J/java" -Xmx8g -Dframework.hedgeOut="$WORK/hedge.tsv" -cp "$WORK/tool:$JAR" io.poly.candor.FrameworkReachGen "$WORK/table.tsv" "$WORK/witness.tsv" "$WORK/header" "${ARGS[@]}"

TABLE="$ROOT/src/main/resources/candor/framework-reach.tsv"
HEDGE="$ROOT/src/main/resources/candor/framework-hedge.tsv"
WIT="$HERE/witness.tsv"
if [ "$CHECK" = 1 ]; then
  if cmp -s "$WORK/table.tsv" "$TABLE" && cmp -s "$WORK/hedge.tsv" "$HEDGE"; then
    echo "derive --check: $TABLE and $HEDGE reproduce byte-identically"; exit 0; fi
  echo "derive --check: $TABLE is NOT what its inputs generate (hand-edited, or stale against this engine):" >&2
  diff "$TABLE" "$WORK/table.tsv" | head -20 >&2; diff "$HEDGE" "$WORK/hedge.tsv" | head -20 >&2
  exit 1
fi
cp "$WORK/table.tsv" "$TABLE"; cp "$WORK/hedge.tsv" "$HEDGE"; cp "$WORK/witness.tsv" "$WIT"
echo "derive: wrote $TABLE ($(grep -vc '^#' "$TABLE") rows) and $WIT — read the diff before committing"
