#!/usr/bin/env bash
# SOUNDNESS R492/R727 — regenerate src/main/resources/candor/framework-reach.tsv from the framework jars' bytecode.
#
#   bash soundness/kappa_table/derive.sh <candor-java-all.jar>            # rewrite the table (+ witness.tsv)
#   bash soundness/kappa_table/derive.sh --check <candor-java-all.jar>    # regenerate to a temp dir; exit 1 on ANY drift
#
# witness.tsv (~130 MB, gitignored — regenerate it, never trust a stale copy) gives, for every charged
# (member, effect), the resolved path from the member to the body this engine's scan charged with that effect.
# Its DIVERGENT lines are the charges present in one surveyed version of an artefact and not another — charged
# nowhere.
#
# INPUTS, and nothing else: the jars named in sources.tsv (Maven Central coordinate + SHA-256 — a jar whose bytes
# differ is REFUSED, never used), this script, FrameworkReachGen.java, jdk-packages.txt (the JDK's packages, a
# checked-in union over JDK images — NOT the running JDK's module list), and the engine jar given as the argument.
# Same inputs -> byte-identical table, whatever JAVA_HOME runs it and whatever CANDOR_* the caller's shell exports
# (both were unpinned inputs until 2026-10-09: a JDK 17 run and a JDK 21 run wrote different `J` lines, and a
# chained CANDOR_DEPS report turns a scan's `Unknown` into effects, which moves `U`/`A` hedge lines). The engine is an input on purpose: the table is built from ITS `direct`
# effects, so a classifier change that moves a charge makes `--check` fail until the table is regenerated.
#
# Steps: fetch/verify every jar; scan each with the engine under -Dcandor.frameworkReach=off (the table never
# feeds its own generation); close every consumer-callable member of every public class under a
# Rules.KAPPA_COVERED_PREFIXES prefix over statically-resolved edges (FrameworkReachGen.java says exactly which);
# write the table, whose header records sources.tsv and the generator checksum, and witness.tsv.
# Read the diff before committing: every new row is a new charge on every caller of that member.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/../.." && pwd)"
LIB="${CANDOR_SOUNDNESS_LIB:-$ROOT/soundness/lib}"
# The scans read the caller's environment: CANDOR_DEPS chains reports, CANDOR_CONFIG / a `.candor/config` above
# $LIB sets scan keys, CANDOR_POLICY a policy, and the JVM option variables can inject -D properties. None of them
# is an input of the table, so none survives into it: every CANDOR_* is unset, and config discovery is pinned to
# an EMPTY file (the explicit override beats the walk up from the jar).
while read -r v; do unset "$v"; done < <(compgen -e | grep -E '^(CANDOR_|JAVA_TOOL_OPTIONS$|_JAVA_OPTIONS$|JDK_JAVA_OPTIONS$)' || true)
CHECK=0; if [ "${1:-}" = "--check" ]; then CHECK=1; shift; fi
JAR="$(cd "$(dirname "${1:?usage: derive.sh [--check] <candor-java-all.jar>}")" && pwd)/$(basename "$1")"
J="${JAVA_HOME:-/opt/homebrew/opt/openjdk@21}/bin"
JOBS="${JOBS:-6}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$LIB" "$WORK/rep" "$WORK/tool"
: > "$WORK/empty-config"; export CANDOR_CONFIG="$WORK/empty-config"
JDKP="$HERE/jdk-packages.txt"

# 1. sources: fetch what is missing, refuse what does not match
while IFS=$'\t' read -r jar coord url sha; do
  [ -z "$jar" ] && continue
  if [ ! -s "$LIB/$jar" ]; then curl -fsSL --retry 3 -o "$LIB/$jar.part" "$url" && mv "$LIB/$jar.part" "$LIB/$jar"; fi
  got="$(shasum -a 256 "$LIB/$jar" | cut -d' ' -f1)"
  if [ "$got" != "$sha" ]; then echo "derive: $jar is $got, sources.tsv pins $sha ($coord) — refusing" >&2; exit 1; fi
done < "$HERE/sources.tsv"

# 1b. SOUNDNESS R1052 — the P list: members a NAME rule charges whose surveyed body is proven pure. Its first cut is
# read from the BYTECODE alone (no scan) and handed to the scans below, because with the table off a library body that
# calls such a member must not pick up the rule's charge either, or the table would re-learn it. Whether a member's
# RETURN type is inert needs the closed effects, which need the scans — so steps 2-4 iterate until the generator
# reproduces the list it was given. It only shrinks (a dropped P line restores a charge), so this terminates.
"$J/javac" -nowarn -cp "$JAR" -d "$WORK/tool" "$HERE/FrameworkReachGen.java"
PJARS=(); for jar in $(cut -f1 "$HERE/sources.tsv"); do PJARS+=("$LIB/$jar"); done
"$J/java" -Xmx8g -Dframework.jdkPackages="$JDKP" -cp "$WORK/tool:$JAR" io.poly.candor.FrameworkReachGen --pure-only "$WORK/pure.txt" "${PJARS[@]}"

# 3. header: the generator checksum and every source, so a table always says what it was built from
GSHA="$(cat "$HERE/FrameworkReachGen.java" "$HERE/derive.sh" "$HERE/sources.tsv" "$HERE/jdk-packages.txt" | shasum -a 256 | cut -d' ' -f1)"
{
  echo "# candor framework-reach table — GENERATED by soundness/kappa_table/derive.sh; DO NOT EDIT (SOUNDNESS R492/R727)."
  echo "# owner.name+desc <TAB> effects: in every surveyed artefact declaring the owner, the statically-resolved body"
  echo "# reaches a body this engine's scan charged with those effects (direct, concrete only). A member with NO row"
  echo "# is not claimed pure: it keeps the treatment it had without this table."
  echo "# NAMED MISS: the closure stops at the JDK, which is OPAQUE here (no bodies; only the classifier's name rules),"
  echo "# while framework bodies are TRANSPARENT. A framework member whose effect happens inside a JDK body the"
  echo "# classifier leaves uncharged is missed exactly as a direct call to that JDK member is (R814 is that frontier)."
  echo "# generator-sha256 $GSHA"
  while IFS=$'\t' read -r jar coord url sha; do [ -n "$jar" ] && echo "# source $coord $sha"; done < "$HERE/sources.tsv"
} > "$WORK/header"

export J JAR LIB WORK
ARGS=()
for jar in $(cut -f1 "$HERE/sources.tsv"); do ARGS+=("$LIB/$jar" "$WORK/rep/$jar.json"); done
iter=0
while :; do
  iter=$((iter + 1))
  [ "$iter" -le 6 ] || { echo "derive: the P list did not reach a fixed point in 6 rounds" >&2; exit 1; }
  # 2. the engine's own scan of each jar, table OFF, the current P list ON
  rm -f "$WORK"/rep/*.json
  cut -f1 "$HERE/sources.tsv" | sed '/^$/d' | (cd "$WORK" && xargs -P "$JOBS" -n 1 sh -c \
    '"$J/java" -Xmx4g -Dcandor.frameworkReach=off -Dcandor.frameworkPure="$WORK/pure.txt" -jar "$JAR" "$LIB/$0" --json "$WORK/rep/$0.json" >/dev/null 2>"$WORK/rep/$0.err" || { echo "derive: scan of $0 failed" >&2; exit 255; }')
  for jar in $(cut -f1 "$HERE/sources.tsv"); do
    [ -s "$WORK/rep/$jar.json" ] || { echo "derive: no report for $jar" >&2; exit 1; }
  done
  # 4. generate (and the next P list)
  "$J/java" -Xmx8g -Dframework.jdkPackages="$JDKP" -Dframework.hedgeOut="$WORK/hedge.tsv" -Dframework.pureIn="$WORK/pure.txt" -Dframework.pureOut="$WORK/pure.next" \
    -cp "$WORK/tool:$JAR" io.poly.candor.FrameworkReachGen "$WORK/table.tsv" "$WORK/witness.tsv" "$WORK/header" "${ARGS[@]}"
  if cmp -s "$WORK/pure.txt" "$WORK/pure.next"; then break; fi
  echo "derive: P list round $iter: $(wc -l < "$WORK/pure.txt") -> $(wc -l < "$WORK/pure.next")" >&2
  mv "$WORK/pure.next" "$WORK/pure.txt"
done

TABLE="$ROOT/src/main/resources/candor/framework-reach.tsv"
HEDGE="$ROOT/src/main/resources/candor/framework-hedge.tsv"
WIT="$HERE/witness.tsv"
if [ "$CHECK" = 1 ]; then
  if cmp -s "$WORK/table.tsv" "$TABLE" && cmp -s "$WORK/hedge.tsv" "$HEDGE"; then
    echo "derive --check: $TABLE and $HEDGE reproduce byte-identically"; exit 0; fi
  echo "derive --check: $TABLE is NOT what its inputs generate (hand-edited, or stale against this engine):" >&2
  diff "$TABLE" "$WORK/table.tsv" | head -20 >&2; diff "$HEDGE" "$WORK/hedge.tsv" | head -20 >&2
  exit 1
fi
cp "$WORK/table.tsv" "$TABLE"; cp "$WORK/hedge.tsv" "$HEDGE"; cp "$WORK/witness.tsv" "$WIT"
echo "derive: wrote $TABLE ($(grep -vc '^#' "$TABLE") rows) and $WIT — read the diff before committing"
